// GENERATED by tools/finger_linkage.py --scad. Do not edit: change the script and re-run.
C_OFF = [-7.0, 6.0];   // coupling pivot on M (behind PIP, dorsal)
G_OFF = [-3.0, -8.0];   // coupling pivot on the palm (behind MCP, palmar)
D_R = 12.0;
HORN_R = 10.0;
SERVO_Z = -40.0;
LAYER_Y = 8.0;
// Per finger: [L1, L2, coupling link, drive rod, layer, drive-pin angle, horn angle when straight]
// Angles in the finger plane, degrees from +z towards +y (dorsal).
FINGER_INDEX = [42.0, 46.0, 40.50, 39.56, "dorsal", 132.5, 136];
FINGER_MIDDLE = [46.0, 50.0, 44.27, 39.66, "palmar", -47.5, -30];
FINGER_RING = [44.0, 48.0, 42.38, 39.66, "palmar", -47.5, -30];
FINGER_PINKY = [34.0, 38.0, 33.11, 39.56, "dorsal", 132.5, 136];
FINGER_THUMB = [36.0, 40.0, 34.93, 0, "direct", 0, 0];
// Glove: operator's finger plane, origin on the operator's MCP axis ([z, y]).
GLOVE_RING = [20.0, 16.0];
GLOVE_POT = [0.0, 26.0];
GLOVE_CRANK = 18.0;
GLOVE_LINK = 34.41;
